##
# Server
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.server
# https://github.com/spring-projects/spring-restdocs/issues/710
# https://www.baeldung.com/exception-handling-for-rest-with-spring#spring-boot
# https://reflectoring.io/spring-boot-exception-handling/
##
server:
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param
        include-exception: false
    port: 8080
    servlet:
        context-path: /

##
# Spring Application
##
spring:

    kafka:
        bootstrap-servers: 127.0.0.1:9092
        producer:
            topic: books
            client-id: book_api
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            topic: books
            group-id: book_api
            auto-offset-reset: earliest
            enable-auto-commit: false
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "stack.edu.Demo.samples.kafka"

    redis:
        host: localhost
        port: 6379
        password: password
    cache:
        type: redis
    output:
        ansi:
            enabled: ALWAYS
    ##
    # Zalando Problem Spring Web
    # https://github.com/zalando/problem-spring-web/issues/732
    ##
    web:
        resources:
            add-mappings: false
    mvc:
        throw-exception-if-no-handler-found: true

##
# Spring Actuator
# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints
##
management:
    endpoints:
        jmx:
            exposure:
                include: "*"
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always
            show-components: always
            ##
            # Kubernetes Probes
            # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.kubernetes-probes
            ##
            probes:
                enabled: true
                add-additional-paths: true
cloud:
    aws:
        
        s3:
            bucket-name: my-bucket
            endpoint: http://127.0.0.1:4566
        stack:
            auto: false
            enabled: false
        credentials:
            access-key: localstackAccessKeyId
            secret-key: localstackSecretAccessKey
        region:
            static: eu-west-1

logging.level.com.amazonaws.services.s3: debug
logging.level.com.amazonaws.util.EC2MetadataUtils: error
##
# Spring Cloud AWS
# https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/appendix.html
##
cloud:
    aws:
        stack:
            auto: false
            enabled: false
        credentials:
            access-key: localstackAccessKeyId
            secret-key: localstackSecretAccessKey
        region:
            static: sa-east-1
        sns:
            endpoint: http://localhost:4566
            region: sa-east-1
            verification: true

logging:
    level:
        io.awspring.cloud.messaging.core: info
        io.awspring.cloud.messaging.listener: info
        com.amazonaws.services.sns: debug

# Samples configuration
samples.aws.sns.publisher-topic: paymentConfirmedTopic
##
# Spring Cloud AWS
# https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/appendix.html
##
cloud:
    aws:
        stack:
            auto: false
            enabled: false
        credentials:
            access-key: localstackAccessKeyId
            secret-key: localstackSecretAccessKey
        region:
            static: sa-east-1
        sqs:
            endpoint: http://localhost:4566
            listener:
                auto-startup: true
                fail-on-missing-queue: false
                default-deletion-policy: NO_REDRIVE
                max-number-of-messages: 10
                visibility-timeout: 30  # 30s
                wait-timeout: 20        # 20s
                back-off-time: 10000    # 10s

logging:
    level:
        io.awspring.cloud.messaging.core: info
        io.awspring.cloud.messaging.listener: info
        com.amazonaws.services.sqs: debug

# Samples configuration
samples.aws.sqs.producer-queue: newProductsQueue
samples.aws.sqs.consumer-queue: customersCreatedQueue
logging.level.org.springframework.cache: TRACE